name: Terminate EC2

on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: "EC2 Instance ID"
        required: true

jobs:
  terminate:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terminate Instance
        run: |
          aws ec2 terminate-instances \
            --instance-ids ${{ github.event.inputs.instance_id }}