name: Maven CI

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Application
        run: mvn clean install

      - name: Create File
        run: |
          echo "hello" > build.txt
          ls -la
        
      - name: Show Workspace
        run: |
          hostname
          pwd
          echo $GITHUB_WORKSPACE

  Testing:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Execute Tests
        run: mvn test

      - name: Show Workspace
        run: |
          hostname
          pwd
          echo $GITHUB_WORKSPACE
      
      - name: List Files
        run: |
          ls -la
          cat build.txt

      